config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :parse_contents, only: [:show, :create, :index, :new]

end

app/models/parse_content.rb
class ParseContent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
  def index
  end
end

app/controllers/parse_contents_controller.rb
class ParseContentsController < ApplicationController  
  require 'nokogiri'   
  require 'open-uri'

  def new
    @parse_content = ParseContent.new
  end

  def index
    @parse_contents = ParseContent.all
  end

  def create
    
    begin
      page = Nokogiri::HTML(open( params[:parse_content][:url] ))
      source = page.css("h1,h2,h3,a")
      content = ""  
      source.each do |element|
        content << element.content
      end
      parse_content = ParseContent.create( url: params[:parse_content][:url], content: content )
      redirect_to parse_content_path(parse_content)
    rescue
      redirect_to :back, alert: "not a valid url"
    end    

  end

  def show
    @parse_content = ParseContent.find_by(params[:id])
  end

  # def parse_content
  
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="head"><h2>LimCoding</h2></div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer_link.html.erb
<div class="footer row">
  <div class="col-md-12">
    <hr>
    <%= link_to :Home, "/"%> | <%= link_to :Index, parse_contents_path %> | <%= link_to "New Parse Url",new_parse_content_path %>
    <hr>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LimTestCoding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/flash_message", flash: flash %> 
  <div class="container">
    <%= yield %>
    <%= render partial: "layouts/footer_link" %>
  </div>  
</body>
</html>

app/views/parse_contents/index.html.erb
<div class="container">
  <div class="head">
    <h2>Listing</h2>
  </div>
  <% if @parse_contents.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Url</th>
          <th>Content</th>        
        </tr>
      </thead>
      <tbody>
        <% @parse_contents.each do |parse_content| %>
          <tr>
            <td><%= parse_content.try(:url) %></td>
            <td><%= parse_content.try(:content) %></td>
          </tr>
        <% end %>      
      </tbody>
    </table>
  <% else %>  
    No data.
  <% end %>
</div>

app/views/parse_contents/new.html.erb
<%= form_for @parse_content do |f| %>
  <div class="container">
    <div class="head">
      <h2>Parse Content</h2>
    </div>
    <%= f.text_field :url, placeholder: :url, required: true %>  
    <br/>
    <%=f.submit %>
  </div>
<%end%>

app/views/parse_contents/show.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12 lead"> <%= @parse_content.url %><hr></div>
        </div>    
        <div class="row">          
          <div class="col-md-12">
            <div class="row">                            
              <span class="text-muted">content:</span> <%= @parse_content.content %><br>
            </div>
          </div>
        </div>      
      </div>
    </div>
  </div>
</div>